version: 2
project_name: pipeleak
builds:
  -
    id: "pipleak"
    dir: ./src/pipeleak/
    binary: pipeleak
    env:
      - CGO_ENABLED=1
    goos:
      - linux
      - windows
    goarch:
      - amd64
      - arm64