name: release

on:
  pull_request:
  push:
    tags:
      - "*"

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    env:
      flags: ""
    steps:
      - if: ${{ !startsWith(github.ref, 'refs/tags/v') }}
        run: echo "flags=--snapshot" >> $GITHUB_ENV
      -
        name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      -
        name: Set up Go
        uses: actions/setup-go@v5
      -
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          args: release --clean --verbose -f goreleaser.yaml ${{ env.flags }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - 
        name: Install binst (binstaller)
        run: |
          go install github.com/binary-install/binstaller/cmd/binst@latest
      - 
        name: Embed checksums for generated release assets
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          binst embed-checksums --config binstaller.yml --tag "${GITHUB_REF##*/}"
      - 
        name: Generate installer script
        run: |
          binst gen --config binstaller.yml --output dist/install-pipeleak.sh
      -
        name: Upload assets
        uses: actions/upload-artifact@v4
        with:
          name: Pipeleak
          path: ./dist/*