name: release
on:
  push:
    branches:
      - 'cgo-builds'
  release:
    types: [created]

permissions:
    contents: write
    packages: write

env:
  CGO_ENABLED: 1

jobs:
  release-nix-platforms:
    name: release builds
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux]
        goarch: [amd64, arm64]
    steps:
    - uses: actions/checkout@v4
    - uses: wangyoucao577/go-release-action@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}
        project_path: ./src/pipeleak

  release-win-platforms:
    name: release builds
    runs-on: windows-latest
    strategy:
      matrix:
        goos: [windows]
        goarch: [amd64]
    steps:
    - uses: actions/checkout@v4
    - uses: wangyoucao577/go-release-action@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}
        project_path: ./src/pipeleak